layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: jasirkt.31
  # hackerrank: your_username
  instagram: jasirkt
  # keybase: your_username
  linkedin: jasirkt
  # mastodon: your_username
  medium: jasirkt
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: jasir_kt
  # unsplash: your_username
  # vk: your_username
  website: https://jasir.dev
  # youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/css
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: MySQL

  - name: React.js
    #web_url: https://github.com/topics/sass
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
